AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  events

  SAM Template for an events microservice

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    TracingEnabled: True
  Function:
    Timeout: 20
    Tracing: Active

Resources:
  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1

  EventsMsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: events-ms
      Handler: io.devwidgets.events.api.lambda.LambdaHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      AutoPublishAlias: Latest
      ReservedConcurrentExecutions: 5
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Events:
        ProxyApiGreedy:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiDeployment
      Policies:
        - Statement:
            - Sid: DynamoDBReadPolicy
              Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Scan
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${EventsDynamoDbTable}
      Tags:
        channel: presentation
        series: serverless-mvp
        episode: reInvent

  EventsDynamoDbTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: EventDetails
      Tags:
        channel: presentation
        series: serverless-mvp
        episode: reInvent

Outputs:
  EventsMsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ApiDeployment}.execute-api.${AWS::Region}.amazonaws.com/v1/events/"
  EventsMsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt EventsMsFunction.Arn
  EventsMsFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt EventsMsFunctionRole.Arn
