package io.devwidgets.events.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import io.devwidgets.events.domain.model.dbconverter.OffsetDateTimeConverter;

import java.time.OffsetDateTime;

@DynamoDBTable(tableName = "Events")
public class Event {
  private String id;
  private String description;
  private OffsetDateTime date;

  @DynamoDBHashKey(attributeName = "Id")
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  @DynamoDBAttribute(attributeName = "Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  @DynamoDBAttribute(attributeName = "Date")
  @DynamoDBTypeConverted(converter = OffsetDateTimeConverter.class)
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }
}
